In [1]:
# !pip install numpy

You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m pip install --upgrade pip' command.


In [7]:
import numpy as np

In [5]:
a = [1,3,4,5,6,6]
b = [1,3,4,5,6,6]
c = [x+y for x,y in zip(a,b)]
c

[2, 6, 8, 10, 12, 12]

In [8]:
arr1 = np.array(a)
arr2 = np.array(b)

In [9]:
arr1+arr2

array([ 2,  6,  8, 10, 12, 12])

In [14]:
a* 2
mul = [x* 2 for x in a] 
val = []
for i in a:
    val.append(i*2)
mul
val

[2, 6, 8, 10, 12, 12]

In [16]:
arr1* 2  #propagation or broadcasting


array([ 2,  6,  8, 10, 12, 12])

In [20]:
arr = np.array([ 2,  6,  8, 10, 12, 12])  # <---

In [22]:
arr.ndim

0

In [23]:
arr1 = np.array([[1,2],[3,4],[5,6]])

In [26]:
arr1.ndim 

2

In [27]:
# rows and col
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
arr1.shape

(3, 2)

In [37]:
arr2 = np.array([[1,2,3],[3,4,3],[5,6,3],[5,6,3],[5,6,3],[5,6,3],[5,6,3],[5,6,5]])

In [34]:
arr2.shape

(8, 3)

In [38]:
arr2.T

array([[1, 3, 5, 5, 5, 5, 5, 5],
       [2, 4, 6, 6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3, 3, 3, 5]])

In [39]:
# [1,2,3,4, 'yes', 'no']
# [int]
# [str]
arr2

array([[1, 2, 3],
       [3, 4, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 5]])

In [40]:
arr2.transpose()

array([[1, 3, 5, 5, 5, 5, 5, 5],
       [2, 4, 6, 6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3, 3, 3, 5]])

In [41]:
int #--> int64 int32 int16 
str  
bool 

bool

In [42]:
arr1.dtype

dtype('int64')

In [50]:
arr1.astype(bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [51]:
period = [1990,1992,1993,1994]
amount1 = [200,300,100,200]
amount2 = [20,300,2000,10]

In [53]:
array1 = np.array([period,amount1])
array2 = np.array([period,amount2])

In [55]:
some = []
for x,y in zip(amount1,amount2):
    if x> y:
        some.append(x)
    else:
        some.append(y)

In [57]:
np.maximum(amount1,amount2)

array([ 200,  300, 2000,  200])