In [1]:
# !pip install numpy

You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m pip install --upgrade pip' command.


In [7]:
import numpy as np

In [5]:
a = [1,3,4,5,6,6]
b = [1,3,4,5,6,6]
c = [x+y for x,y in zip(a,b)]
c

[2, 6, 8, 10, 12, 12]

In [8]:
arr1 = np.array(a)
arr2 = np.array(b)

In [9]:
arr1+arr2

array([ 2,  6,  8, 10, 12, 12])

In [14]:
a* 2
mul = [x* 2 for x in a] 
val = []
for i in a:
    val.append(i*2)
mul
val

[2, 6, 8, 10, 12, 12]

In [16]:
arr1* 2  #propagation or broadcasting


array([ 2,  6,  8, 10, 12, 12])

In [20]:
arr = np.array([ 2,  6,  8, 10, 12, 12])  # <---

In [22]:
arr.ndim

0

In [23]:
arr1 = np.array([[1,2],[3,4],[5,6]])

In [26]:
arr1.ndim 

2

In [27]:
# rows and col
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
arr1.shape

(3, 2)

In [37]:
arr2 = np.array([[1,2,3],[3,4,3],[5,6,3],[5,6,3],[5,6,3],[5,6,3],[5,6,3],[5,6,5]])

In [34]:
arr2.shape

(8, 3)

In [38]:
arr2.T

array([[1, 3, 5, 5, 5, 5, 5, 5],
       [2, 4, 6, 6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3, 3, 3, 5]])

In [39]:
# [1,2,3,4, 'yes', 'no']
# [int]
# [str]
arr2

array([[1, 2, 3],
       [3, 4, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 3],
       [5, 6, 5]])

In [40]:
arr2.transpose()

array([[1, 3, 5, 5, 5, 5, 5, 5],
       [2, 4, 6, 6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3, 3, 3, 5]])

In [41]:
int #--> int64 int32 int16 
str  
bool 

bool

In [42]:
arr1.dtype

dtype('int64')

In [50]:
arr1.astype(bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [51]:
period = [1990,1992,1993,1994]
amount1 = [200,300,100,200]
amount2 = [20,300,2000,10]

In [53]:
array1 = np.array([period,amount1])
array2 = np.array([period,amount2])

In [55]:
some = []
for x,y in zip(amount1,amount2):
    if x> y:
        some.append(x)
    else:
        some.append(y)

In [57]:
np.maximum(amount1,amount2)

array([ 200,  300, 2000,  200])

In [65]:
import numpy as np
import pandas as pd
a = np.array([["M", 86],
              ["M", 76],
              ["M", 56],
              ["M", 66],
              ["B", 16],
              ["B", 13],
              ["B", 16],
              ["B", 18],
              ["B", 14], ])
df = pd.DataFrame(data=a, columns=["Case", "radius"])
df['radius']= df['radius'].astype('int')



a = df[(df["radius"] >= 57)]["radius"].tolist()
print(a)

[86, 76, 66]


In [59]:
df["radius"]

0    86
1    76
2    56
3    66
4    16
5    13
6    16
7    18
8    14
Name: radius, dtype: object

In [71]:
companies = {
    'CoolCompany' : {'Alice' : 33, 'Bob' : 28, 'Frank' : 29},
    'CheapCompany' : {'Ann' : 4, 'Lee' : 9, 'Chrisi' : 7},
    'SosoCompany' : {'Esther' : 38, 'Cole' : 8, 'Paris' : 18}}
## One-Liner
illegal = [x for x in companies if any(y<9 for y in companies[x].values())]
## Result
print(illegal)

['CheapCompany', 'SosoCompany']


In [75]:
## Data: yearly salary in ($1000) [2025, 2026, 2027]
dataScientist =[129, 131, 137]
productManager =[130, 132, 137]
designer = [127, 140, 145]
softwareEngineer = [118, 118, 127]



employees = np.array([dataScientist,
                      productManager,
                      designer,
                      softwareEngineer])
## One-liner
employees[0,::2] = employees[0,::2] * 1.1
## Result
print(employees)

[[141 131 150]
 [130 132 137]
 [127 140 145]
 [118 118 127]]


In [76]:
 employees[0,::2]

array([141, 150])

In [80]:
np.array(dataScientist, dtype =np.int32) * 1.1

array([141.9, 144.1, 150.7])