In [1]:
#  list vs array
#  import 

In [13]:
import numpy as np  
# array oriented

In [15]:
# help(np.array)
arr = np.array([1,2,3,4,5,6])

In [17]:
arr.shape  #tuple value

(6,)

In [18]:
arr.ndim

1

In [19]:
arr.dtype

dtype('int64')

In [28]:
# help(np.zeros)
zero = np.zeros((3,3), dtype=int)

In [29]:
zero + 1  # broadcasting

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
one = np.ones((6,6), dtype =int)  #
one.ndim # rows and columns
one.shape

(6, 6)

In [40]:
# int str bool
# casting
value = int('10')
print(type(value))

<class 'int'>


In [41]:
np.array(['10','2'], dtype = int)

array([10,  2])

In [42]:
arr_str = np.array(['10','2'])

In [44]:
new = arr_str.astype(int)
new.dtype

dtype('int64')

In [66]:
 #data copying 
df1 = [1,2,3,4,5]  #raw_data
df2 = df1  #processing
print(df2)

[1, 2, 3, 4, 5]


In [73]:
print(df1 is df1 )# checks the memory location
print(df1 == df1 )# just checks the value
print(id(df1), id(df2))

True
True
140597119326016 140597119326016


In [75]:
print(a)

[1, 2, 3, 4, 5]


In [78]:
new_df = [1,2,3,4,5]
new_df1 = [*new_df]

In [79]:
print(new_df is new_df1 )   # checks the memory location
print(new_df == new_df1 )
print(id(new_df), id(new_df1))

True
True
140597132650048 140597132650048


In [70]:
new_df1

[1, 2, 3, 4, 5]

In [82]:
c = [*df1,*df2]

In [83]:
print(c)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [93]:
raw_data = ['sam', 'johnzes', 'lukey'] # array
proc= [*raw_data  ]# copy 

In [91]:
proc[0]= 'Samz'

In [92]:
raw_data

['Samz', 'johnzes', 'lukey']

In [102]:
arr1 = np.ones((2,6),dtype= int)

In [103]:
c = arr1

In [104]:
c[0,2]= 12232323

In [113]:
print(arr1)
print(c)

[[       1        1 12232323        1        1        1]
 [       1        1        1        1        1        1]]
[[       1        1 12232323        1        1        1]
 [       1        1        1        1        1        1]]


In [106]:
d = arr1.copy()

In [109]:
d[1,3]= 2929

In [112]:
print(arr1)
print(d)

[[       1        1 12232323        1        1        1]
 [       1        1        1        1        1        1]]
[[       1        1 12232323        1        1        1]
 [       1        1        1     2929        1        1]]


In [116]:
one_dime =np.array([1,2,3,4,5])

In [118]:
one_dime[0]

1

In [129]:
two_dime =np.array([[1,2,3,4,5],[6,7,8,9,20]] )

In [132]:
# help(np.array)
two_dime.ndim
two_dime

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20]])

In [137]:
two_dime[1][3]

9

In [138]:
two_dime[1,3]  #row,#col

9

In [141]:
arr1 = arr1.T

In [144]:
arr1.shape

(6, 2)

In [145]:
arr1

array([[       1,        1],
       [       1,        1],
       [12232323,        1],
       [       1,        1],
       [       1,        1],
       [       1,        1]])

In [149]:
arr1[:3, 0:2]  #[start: end, (start) : End]

array([[       1,        1],
       [       1,        1],
       [12232323,        1]])

In [150]:
arr1[3:, :]

array([[1, 1],
       [1, 1],
       [1, 1]])

In [155]:
# bool
arr_bool = np.random.randn(6,6)
arr_bool2 = np.random.randn(6,6)

In [161]:
arr_bool

array([[-0.07263848,  1.29578855, -0.74224624,  0.69709998,  0.17120003,
        -0.26412001],
       [ 1.40726391,  0.37412456,  1.4917217 , -1.34352589, -0.11942445,
         0.45176154],
       [ 1.22204194,  0.81500303,  0.03130439,  0.57145688, -0.20859763,
        -1.6017953 ],
       [-0.22366302,  0.53991314, -0.09544961,  0.22513896,  0.7487023 ,
        -0.25718985],
       [-1.70424825, -1.08437612, -1.05070753,  0.02225055,  0.54659332,
         0.57300584],
       [ 0.20087792,  0.01906241,  1.20380624,  1.20658386,  0.07450949,
         0.73150938]])

In [166]:
bol_arr = arr_bool2 < 0.12

In [167]:
arr_bool2[bol_arr]

array([-0.33515804, -0.2669494 , -0.64019929, -0.42338303, -0.7513598 ,
       -0.35073116, -0.57454724, -0.24457216, -1.05417775, -0.95604295,
       -0.77802719, -0.28485969, -0.59943001, -0.18613751, -0.21405335,
        0.07815983, -1.87875788, -0.51237517])

In [173]:
names = 'Ade Sam Luke James John Mike Sandy Sarah Jane'.split(' ')
occup = 'footballer Musciain Movie_producer Actor Engr Teacher Musciain Movie_producer Doctor'.split(' ')

In [175]:
name_np = np.array(names)
occup_np = np.array(occup)

In [179]:
filt = occup_np == 'Musciain'

In [180]:
name_np[filt]

array(['Sam', 'Sandy'], dtype='<U5')

In [181]:
non_mus = occup_np != 'Musciain'

In [183]:
name_np[non_mus]  # array of values thats returns true

array(['Ade', 'Luke', 'James', 'John', 'Mike', 'Sarah', 'Jane'],
      dtype='<U5')

In [184]:
# !=
# ==
# ~ 

In [186]:
name_np[~ non_mus]  # 

array(['Sam', 'Sandy'], dtype='<U5')

In [187]:
test = np.array([1,2])
test2 = np.array([3,4])

In [190]:
test[test2 == 3]

array([1])

In [197]:
arr_bool[[1,5], 4] #fancy indexing

array([-0.11942445,  0.07450949])

In [193]:
arr_bool

array([[-0.07263848,  1.29578855, -0.74224624,  0.69709998,  0.17120003,
        -0.26412001],
       [ 1.40726391,  0.37412456,  1.4917217 , -1.34352589, -0.11942445,
         0.45176154],
       [ 1.22204194,  0.81500303,  0.03130439,  0.57145688, -0.20859763,
        -1.6017953 ],
       [-0.22366302,  0.53991314, -0.09544961,  0.22513896,  0.7487023 ,
        -0.25718985],
       [-1.70424825, -1.08437612, -1.05070753,  0.02225055,  0.54659332,
         0.57300584],
       [ 0.20087792,  0.01906241,  1.20380624,  1.20658386,  0.07450949,
         0.73150938]])

In [199]:
arr_bool.sum()

5.852737515871611

In [204]:
test.cumsum()

array([1, 3])

In [205]:
test

array([1, 2])

In [208]:
np.add(test,test2)

array([4, 6])

In [219]:
# imitation of conditionals in numpy

# if condition is True:
# #     do something
# else:
# #     do something else

In [246]:
number = [x for x in range(1000)]
import time


In [243]:
start = time.perf_counter()
even = []
even1 = []

for x in number:
    if x%2 ==0:
        even.append(x)
end = time.perf_counter()
print(end-start)

comp = [x for x in number if x% 2==0 ] #comp = [even1.append(x) for x in number if x% 2==0 ] #

10.396228915999927


In [222]:
# select and where
# help(np.where)

In [224]:
# np.where(cond,[x,y])


In [244]:
start = time.perf_counter()

cond = x % 2 ==0
filterr = np.where(cond,True,False)
x[filterr]
end= time.perf_counter()
print(end-start)

7.4575243269991915


In [249]:
x = np.array(number)
condition = [x % 2 ==0]
choice = [True]
new = np.select(condition,choice, default=False)

In [250]:
x[new]

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [ ]:
# missing_data value = 1000 gender/salary
mean